version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
        name: Install Vendor
        command: composer install

      - run:
        name: Code Style
        command: make tests