index:
  path: /
  controller: App\Controller\IndexController::index
blog:
  resource: 'routes/blog.yaml'
  prefix: '/blog'

registration:
  resource: 'routes/registration.yaml'
  prefix: '/registration'

login:
  resource: 'routes/login.yaml'
  prefix: '/login'