index:
  path: /
  controller: App\Controller\IndexController::index
blog:
  resource: 'routes/blog.yaml'
  prefix: '/blog'

registration:
  resource: 'routes/registration.yaml'
  prefix: '/registration'

login:
  path: /login
  controller: App\Controller\SecurityController::login
  #resource: 'routes/login.yaml'
  #prefix: '/login'

password:
  resource: 'routes/password.yaml'
  prefix: '/password'