default:
  path: /
  controller: App\Controller\IndexController::index

articles:
  resource: 'routes/article.yaml'
  prefix: '/articles'

comment:
  resource: 'routes/comment.yaml'
  prefix: '/comment'

blog:
  resource: 'routes/blog.yaml'
  prefix: '/blog'

registration:
  resource: 'routes/registration.yaml'
  prefix: '/registration'

login:
  path: /login
  controller: App\Controller\SecurityController::login
  #resource: 'routes/login.yaml'
  #prefix: '/login'

password:
  resource: 'routes/password.yaml'
  prefix: '/password'

user:
  resource: 'routes/user.yaml'
  prefix: '/user'