registration:
  resource: 'routes/registration.yaml'
  prefix: '/registration'

login:
  path: /login
  controller: App\Controller\SecurityController::login

password:
  resource: 'routes/password.yaml'
  prefix: '/password'