#index:
#    path: /
#    controller: App\Controller\DefaultController::index
blog:
  resource: 'routes/blog.yaml'
  prefix: '/blog'

registration:
  resource: 'routes/registration.yaml'
  prefix: '/registration'

login:
  path: /login
  controller: App\Controller\SecurityController::login
  #resource: 'routes/login.yaml'
  #prefix: '/login'

password:
  resource: 'routes/password.yaml'
  prefix: '/password'

bet:
  resource: 'routes/bet/bet.yaml'
  prefix: '/bet'

mail:
  resource: 'routes/mail/mail.yaml'
  prefix: 'mail/'

partyResult:
  resource: 'routes/partyResult/partyResult.yaml'
  prefix: 'partyResult'